export const RATINGS_REPOSITORY = Symbol('RATINGS_REPOSITORY');
export const ACTIVITY_RECORDS_REPOSITORY = Symbol(
  'ACTIVITY_RECORDS_REPOSITORY',
);
export const SYMPTOM_RECORDS_REPOSITORY = Symbol(
  'SYMPTOM_RECORDS_REPOSITORY',
);
export const ACTIVITIES_REPOSITORY = Symbol('ACTIVITIES_REPOSITORY');
export const SYMPTOMS_REPOSITORY = Symbol('SYMPTOMS_REPOSITORY');
